version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
configuration: Release
platform: Any CPU
clone_depth: 10
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
    - cmd: nuget restore LinqToQuerystring.Core.sln
build:
  project: LinqToQuerystring.Core.sln
  verbosity: minimal
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: '#builds'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true